### ISSUE TITLE
Add `https://` value to tokens generated from EGA login

### ISSUE THREAD

**Issue by viklund** [NBISweden/sda-auth#25]
The `iss` returned by elixir has the `https://` prefix in it. To make the handling of these things more similar accross our services it would be good if the EGA key did this as well.

From reading the code I assume this can be accomplished in 3 ways:

1. Change the configuration of the service (specifically, the `SERVER_NAME`). This would require no code changes and it might work, _but_ this value is used in other parts of the code so I'm not sure how this would effect other stuff.

1. Prepend `https://` to the `SERVER_NAME` here: https://github.com/NBISweden/sda-auth/blob/master/sda_auth/models.py#L12

1. Add a new configuration parameter `JWT_ISSUER`

I prefer the last one, but there might be other ways or some strong reason to just change the configuration.

**Comment by jonandernovella** [comment]
I will explore these options, but I suspect that, as you pointed, simply changing the server name will not work.
